/* Generated by Yosys 0.14+65 (git sha1 3818e1160, x86_64-conda_cos6-linux-gnu-gcc 1.24.0.133_b0863d8_dirty -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/home/runner/work/conda-eda/conda-eda/workdir/conda-env/conda-bld/yosys_1646263272177/work=/usr/local/src/conda/yosys-0.14_67_g3818e1160 -fdebug-prefix-map=/home/runner/work/conda-eda/conda-eda/workdir/conda-env/conda-bld/yosys_1646263272177/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl=/usr/local/src/conda-prefix -fPIC -Os -fno-merge-constants) */

(* \amaranth.hierarchy  = "Cfu" *)
(* top =  1  *)
(* generator = "Amaranth" *)
module Cfu(cmd_ready, cmd_payload_function_id, cmd_payload_inputs_0, cmd_payload_inputs_1, rsp_valid, rsp_ready, rsp_payload_outputs_0, reset, port0_addr, port1_addr, port2_addr, port3_addr, port0_din, port1_din, port2_din, port3_din, clk, rst, cmd_valid);
  reg \$auto$verilog_backend.cc:2083:dump_module$1  = 0;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:250" *)
  wire [31:0] \$signal ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:251" *)
  wire \$signal$1 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:251" *)
  wire \$signal$10 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:252" *)
  reg \$signal$11 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:250" *)
  wire [31:0] \$signal$12 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:251" *)
  wire \$signal$13 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:252" *)
  reg \$signal$15 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:250" *)
  wire [31:0] \$signal$16 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:251" *)
  wire \$signal$17 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:252" *)
  reg \$signal$19 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:252" *)
  reg \$signal$2 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:250" *)
  wire [31:0] \$signal$20 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:251" *)
  wire \$signal$21 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:252" *)
  reg \$signal$23 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:250" *)
  wire [31:0] \$signal$24 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:251" *)
  wire \$signal$25 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:252" *)
  reg \$signal$27 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:250" *)
  wire [31:0] \$signal$3 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:251" *)
  wire \$signal$4 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:252" *)
  reg \$signal$5 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:250" *)
  wire [31:0] \$signal$6 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:251" *)
  wire \$signal$7 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:252" *)
  reg \$signal$8 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:250" *)
  wire [31:0] \$signal$9 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/third_party/python/amaranth/amaranth/hdl/ir.py:527" *)
  input clk;
  wire clk;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:185" *)
  input [9:0] cmd_payload_function_id;
  wire [9:0] cmd_payload_function_id;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:186" *)
  input [31:0] cmd_payload_inputs_0;
  wire [31:0] cmd_payload_inputs_0;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:187" *)
  input [31:0] cmd_payload_inputs_1;
  wire [31:0] cmd_payload_inputs_1;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:183" *)
  output cmd_ready;
  reg cmd_ready;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:182" *)
  input cmd_valid;
  wire cmd_valid;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:246" *)
  reg current_function_done;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:245" *)
  reg [2:0] current_function_id;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  wire fallback3_done;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  wire [31:0] fallback3_in0;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  wire [31:0] fallback3_in1;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  wire [31:0] fallback3_output;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  wire fallback4_done;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  wire [31:0] fallback4_in0;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  wire [31:0] fallback4_in1;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  wire [31:0] fallback4_output;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  wire fallback5_done;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  wire [31:0] fallback5_in0;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  wire [31:0] fallback5_in1;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  wire [31:0] fallback5_output;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  wire fallback6_done;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  wire [31:0] fallback6_in0;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  wire [31:0] fallback6_in1;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  wire [31:0] fallback6_output;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  wire fallback7_done;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  wire [31:0] fallback7_in0;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  wire [31:0] fallback7_in1;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  wire [31:0] fallback7_output;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  wire fn0_done;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  wire [31:0] fn0_in0;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  wire [31:0] fn0_in1;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  wire [31:0] fn0_output;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:52" *)
  wire fn0_start;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  wire fn1_done;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:50" *)
  wire [6:0] fn1_funct7;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  wire [31:0] fn1_in0;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  wire [31:0] fn1_in1;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  wire [31:0] fn1_output;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:52" *)
  wire fn1_start;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  wire fn2_done;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  wire [31:0] fn2_in0;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  wire [31:0] fn2_in1;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  wire [31:0] fn2_output;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:52" *)
  wire fn2_start;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:272" *)
  reg [1:0] fsm_state = 2'h0;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:272" *)
  reg [1:0] \fsm_state$next ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:238" *)
  wire [2:0] funct3;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:239" *)
  wire [6:0] funct7;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:50" *)
  wire [6:0] \funct7$28 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:50" *)
  wire [6:0] \funct7$29 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:50" *)
  wire [6:0] \funct7$30 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:50" *)
  wire [6:0] \funct7$31 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:50" *)
  wire [6:0] \funct7$32 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:50" *)
  wire [6:0] \funct7$33 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:50" *)
  wire [6:0] \funct7$34 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:192" *)
  input [31:0] port0_addr;
  wire [31:0] port0_addr;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:193" *)
  input [31:0] port0_din;
  wire [31:0] port0_din;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:192" *)
  input [31:0] port1_addr;
  wire [31:0] port1_addr;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:193" *)
  input [31:0] port1_din;
  wire [31:0] port1_din;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:192" *)
  input [31:0] port2_addr;
  wire [31:0] port2_addr;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:193" *)
  input [31:0] port2_din;
  wire [31:0] port2_din;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:192" *)
  input [31:0] port3_addr;
  wire [31:0] port3_addr;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:193" *)
  input [31:0] port3_din;
  wire [31:0] port3_din;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:191" *)
  input reset;
  wire reset;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:190" *)
  output [31:0] rsp_payload_outputs_0;
  reg [31:0] rsp_payload_outputs_0;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:189" *)
  input rsp_ready;
  wire rsp_ready;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:188" *)
  output rsp_valid;
  reg rsp_valid;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/third_party/python/amaranth/amaranth/hdl/ir.py:527" *)
  output rst;
  wire rst;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:52" *)
  wire start;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:52" *)
  wire \start$14 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:52" *)
  wire \start$18 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:52" *)
  wire \start$22 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:52" *)
  wire \start$26 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:244" *)
  reg [2:0] stored_function_id = 3'h0;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:244" *)
  reg [2:0] \stored_function_id$next ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:247" *)
  reg [31:0] stored_output = 32'd0;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:247" *)
  reg [31:0] \stored_output$next ;
  always @(posedge clk)
    stored_function_id <= \stored_function_id$next ;
  always @(posedge clk)
    fsm_state <= \fsm_state$next ;
  always @(posedge clk)
    stored_output <= \stored_output$next ;
  fallback3 fallback3 (
    .done(fallback3_done),
    .in0(fallback3_in0),
    .in1(fallback3_in1),
    .\output (fallback3_output)
  );
  fallback4 fallback4 (
    .done(fallback4_done),
    .in0(fallback4_in0),
    .in1(fallback4_in1),
    .\output (fallback4_output)
  );
  fallback5 fallback5 (
    .done(fallback5_done),
    .in0(fallback5_in0),
    .in1(fallback5_in1),
    .\output (fallback5_output)
  );
  fallback6 fallback6 (
    .done(fallback6_done),
    .in0(fallback6_in0),
    .in1(fallback6_in1),
    .\output (fallback6_output)
  );
  fallback7 fallback7 (
    .done(fallback7_done),
    .in0(fallback7_in0),
    .in1(fallback7_in1),
    .\output (fallback7_output)
  );
  fn0 fn0 (
    .clk(clk),
    .done(fn0_done),
    .in0(fn0_in0),
    .in1(fn0_in1),
    .\output (fn0_output),
    .rst(rst),
    .start(fn0_start)
  );
  fn1 fn1 (
    .clk(clk),
    .done(fn1_done),
    .funct7(fn1_funct7),
    .in0(fn1_in0),
    .in1(fn1_in1),
    .\output (fn1_output),
    .rst(rst),
    .start(fn1_start)
  );
  fn2 fn2 (
    .clk(clk),
    .done(fn2_done),
    .in0(fn2_in0),
    .in1(fn2_in1),
    .\output (fn2_output),
    .rst(rst),
    .start(fn2_start)
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$1 ) begin end
    current_function_id = 3'h0;
    (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:272" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "WAIT_CMD/0" */
      /* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:273" */
      2'h0:
          current_function_id = funct3;
      /* \amaranth.decoding  = "WAIT_INSTRUCTION/2" */
      /* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:284" */
      2'h2:
          current_function_id = stored_function_id;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$1 ) begin end
    current_function_done = 1'h0;
    (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:272" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "WAIT_CMD/0" */
      /* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:273" */
      2'h0:
          (* full_case = 32'd1 *)
          (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:277" *)
          casez (current_function_id)
            3'h0:
                current_function_done = \$signal$1 ;
            3'h1:
                current_function_done = \$signal$4 ;
            3'h2:
                current_function_done = \$signal$7 ;
            3'h3:
                current_function_done = \$signal$10 ;
            3'h4:
                current_function_done = \$signal$13 ;
            3'h5:
                current_function_done = \$signal$17 ;
            3'h6:
                current_function_done = \$signal$21 ;
            3'h?:
                current_function_done = \$signal$25 ;
          endcase
      /* \amaranth.decoding  = "WAIT_INSTRUCTION/2" */
      /* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:284" */
      2'h2:
          (* full_case = 32'd1 *)
          (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:289" *)
          casez (current_function_id)
            3'h0:
                current_function_done = \$signal$1 ;
            3'h1:
                current_function_done = \$signal$4 ;
            3'h2:
                current_function_done = \$signal$7 ;
            3'h3:
                current_function_done = \$signal$10 ;
            3'h4:
                current_function_done = \$signal$13 ;
            3'h5:
                current_function_done = \$signal$17 ;
            3'h6:
                current_function_done = \$signal$21 ;
            3'h?:
                current_function_done = \$signal$25 ;
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$1 ) begin end
    cmd_ready = 1'h0;
    (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:272" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "WAIT_CMD/0" */
      /* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:273" */
      2'h0:
          cmd_ready = 1'h1;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$1 ) begin end
    \stored_function_id$next  = stored_function_id;
    (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:272" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "WAIT_CMD/0" */
      /* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:273" */
      2'h0:
          (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:279" *)
          casez (cmd_valid)
            /* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:279" */
            1'h1:
                \stored_function_id$next  = cmd_payload_function_id[2:0];
          endcase
    endcase
    (* src = "/home/centurion/Documents/Diploma/CFU-Playground/third_party/python/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \stored_function_id$next  = 3'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$1 ) begin end
    \$signal$2  = 1'h0;
    \$signal$5  = 1'h0;
    \$signal$8  = 1'h0;
    \$signal$11  = 1'h0;
    \$signal$15  = 1'h0;
    \$signal$19  = 1'h0;
    \$signal$23  = 1'h0;
    \$signal$27  = 1'h0;
    (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:272" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "WAIT_CMD/0" */
      /* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:273" */
      2'h0:
          (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:279" *)
          casez (cmd_valid)
            /* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:279" */
            1'h1:
                (* full_case = 32'd1 *)
                (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:282" *)
                casez (current_function_id)
                  3'h0:
                      \$signal$2  = 1'h1;
                  3'h1:
                      \$signal$5  = 1'h1;
                  3'h2:
                      \$signal$8  = 1'h1;
                  3'h3:
                      \$signal$11  = 1'h1;
                  3'h4:
                      \$signal$15  = 1'h1;
                  3'h5:
                      \$signal$19  = 1'h1;
                  3'h6:
                      \$signal$23  = 1'h1;
                  3'h?:
                      \$signal$27  = 1'h1;
                endcase
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$1 ) begin end
    rsp_valid = 1'h0;
    (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:272" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "WAIT_CMD/0" */
      /* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:273" */
      2'h0:
          (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:279" *)
          casez (cmd_valid)
            /* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:279" */
            1'h1:
                (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:259" *)
                casez (current_function_done)
                  /* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:259" */
                  1'h1:
                      rsp_valid = 1'h1;
                endcase
          endcase
      /* \amaranth.decoding  = "WAIT_INSTRUCTION/2" */
      /* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:284" */
      2'h2:
          (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:259" *)
          casez (current_function_done)
            /* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:259" */
            1'h1:
                rsp_valid = 1'h1;
          endcase
      /* \amaranth.decoding  = "WAIT_TRANSFER/1" */
      /* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:291" */
      2'h1:
          rsp_valid = 1'h1;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$1 ) begin end
    rsp_payload_outputs_0 = 32'd0;
    (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:272" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "WAIT_CMD/0" */
      /* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:273" */
      2'h0:
          (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:279" *)
          casez (cmd_valid)
            /* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:279" */
            1'h1:
                (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:259" *)
                casez (current_function_done)
                  /* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:259" */
                  1'h1:
                      (* full_case = 32'd1 *)
                      (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:262" *)
                      casez (current_function_id)
                        3'h0:
                            rsp_payload_outputs_0 = \$signal ;
                        3'h1:
                            rsp_payload_outputs_0 = \$signal$3 ;
                        3'h2:
                            rsp_payload_outputs_0 = \$signal$6 ;
                        3'h3:
                            rsp_payload_outputs_0 = \$signal$9 ;
                        3'h4:
                            rsp_payload_outputs_0 = \$signal$12 ;
                        3'h5:
                            rsp_payload_outputs_0 = \$signal$16 ;
                        3'h6:
                            rsp_payload_outputs_0 = \$signal$20 ;
                        3'h?:
                            rsp_payload_outputs_0 = \$signal$24 ;
                      endcase
                endcase
          endcase
      /* \amaranth.decoding  = "WAIT_INSTRUCTION/2" */
      /* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:284" */
      2'h2:
          (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:259" *)
          casez (current_function_done)
            /* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:259" */
            1'h1:
                (* full_case = 32'd1 *)
                (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:262" *)
                casez (current_function_id)
                  3'h0:
                      rsp_payload_outputs_0 = \$signal ;
                  3'h1:
                      rsp_payload_outputs_0 = \$signal$3 ;
                  3'h2:
                      rsp_payload_outputs_0 = \$signal$6 ;
                  3'h3:
                      rsp_payload_outputs_0 = \$signal$9 ;
                  3'h4:
                      rsp_payload_outputs_0 = \$signal$12 ;
                  3'h5:
                      rsp_payload_outputs_0 = \$signal$16 ;
                  3'h6:
                      rsp_payload_outputs_0 = \$signal$20 ;
                  3'h?:
                      rsp_payload_outputs_0 = \$signal$24 ;
                endcase
          endcase
      /* \amaranth.decoding  = "WAIT_TRANSFER/1" */
      /* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:291" */
      2'h1:
          rsp_payload_outputs_0 = stored_output;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$1 ) begin end
    \fsm_state$next  = fsm_state;
    (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:272" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "WAIT_CMD/0" */
      /* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:273" */
      2'h0:
          (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:279" *)
          casez (cmd_valid)
            /* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:279" */
            1'h1:
                (* full_case = 32'd1 *)
                (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:259" *)
                casez (current_function_done)
                  /* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:259" */
                  1'h1:
                      (* full_case = 32'd1 *)
                      (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:263" *)
                      casez (rsp_ready)
                        /* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:263" */
                        1'h1:
                            \fsm_state$next  = 2'h0;
                        /* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:265" */
                        default:
                            \fsm_state$next  = 2'h1;
                      endcase
                  /* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:269" */
                  default:
                      \fsm_state$next  = 2'h2;
                endcase
          endcase
      /* \amaranth.decoding  = "WAIT_INSTRUCTION/2" */
      /* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:284" */
      2'h2:
          (* full_case = 32'd1 *)
          (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:259" *)
          casez (current_function_done)
            /* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:259" */
            1'h1:
                (* full_case = 32'd1 *)
                (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:263" *)
                casez (rsp_ready)
                  /* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:263" */
                  1'h1:
                      \fsm_state$next  = 2'h0;
                  /* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:265" */
                  default:
                      \fsm_state$next  = 2'h1;
                endcase
            /* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:269" */
            default:
                \fsm_state$next  = 2'h2;
          endcase
      /* \amaranth.decoding  = "WAIT_TRANSFER/1" */
      /* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:291" */
      2'h1:
          (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:296" *)
          casez (rsp_ready)
            /* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:296" */
            1'h1:
                \fsm_state$next  = 2'h0;
          endcase
    endcase
    (* src = "/home/centurion/Documents/Diploma/CFU-Playground/third_party/python/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \fsm_state$next  = 2'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$1 ) begin end
    \stored_output$next  = stored_output;
    (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:272" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "WAIT_CMD/0" */
      /* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:273" */
      2'h0:
          (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:279" *)
          casez (cmd_valid)
            /* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:279" */
            1'h1:
                (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:259" *)
                casez (current_function_done)
                  /* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:259" */
                  1'h1:
                      (* full_case = 32'd1 *)
                      (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:263" *)
                      casez (rsp_ready)
                        /* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:263" */
                        1'h1:
                            /* empty */;
                        /* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:265" */
                        default:
                            (* full_case = 32'd1 *)
                            (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:267" *)
                            casez (current_function_id)
                              3'h0:
                                  \stored_output$next  = \$signal ;
                              3'h1:
                                  \stored_output$next  = \$signal$3 ;
                              3'h2:
                                  \stored_output$next  = \$signal$6 ;
                              3'h3:
                                  \stored_output$next  = \$signal$9 ;
                              3'h4:
                                  \stored_output$next  = \$signal$12 ;
                              3'h5:
                                  \stored_output$next  = \$signal$16 ;
                              3'h6:
                                  \stored_output$next  = \$signal$20 ;
                              3'h?:
                                  \stored_output$next  = \$signal$24 ;
                            endcase
                      endcase
                endcase
          endcase
      /* \amaranth.decoding  = "WAIT_INSTRUCTION/2" */
      /* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:284" */
      2'h2:
          (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:259" *)
          casez (current_function_done)
            /* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:259" */
            1'h1:
                (* full_case = 32'd1 *)
                (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:263" *)
                casez (rsp_ready)
                  /* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:263" */
                  1'h1:
                      /* empty */;
                  /* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:265" */
                  default:
                      (* full_case = 32'd1 *)
                      (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:267" *)
                      casez (current_function_id)
                        3'h0:
                            \stored_output$next  = \$signal ;
                        3'h1:
                            \stored_output$next  = \$signal$3 ;
                        3'h2:
                            \stored_output$next  = \$signal$6 ;
                        3'h3:
                            \stored_output$next  = \$signal$9 ;
                        3'h4:
                            \stored_output$next  = \$signal$12 ;
                        3'h5:
                            \stored_output$next  = \$signal$16 ;
                        3'h6:
                            \stored_output$next  = \$signal$20 ;
                        3'h?:
                            \stored_output$next  = \$signal$24 ;
                      endcase
                endcase
          endcase
    endcase
    (* src = "/home/centurion/Documents/Diploma/CFU-Playground/third_party/python/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \stored_output$next  = 32'd0;
    endcase
  end
  assign rst = reset;
  assign \funct7$34  = funct7;
  assign fallback7_in1 = cmd_payload_inputs_1;
  assign fallback7_in0 = cmd_payload_inputs_0;
  assign \funct7$33  = funct7;
  assign fallback6_in1 = cmd_payload_inputs_1;
  assign fallback6_in0 = cmd_payload_inputs_0;
  assign \funct7$32  = funct7;
  assign fallback5_in1 = cmd_payload_inputs_1;
  assign fallback5_in0 = cmd_payload_inputs_0;
  assign \funct7$31  = funct7;
  assign fallback4_in1 = cmd_payload_inputs_1;
  assign fallback4_in0 = cmd_payload_inputs_0;
  assign \funct7$30  = funct7;
  assign fallback3_in1 = cmd_payload_inputs_1;
  assign fallback3_in0 = cmd_payload_inputs_0;
  assign \funct7$29  = funct7;
  assign fn2_in1 = cmd_payload_inputs_1;
  assign fn2_in0 = cmd_payload_inputs_0;
  assign fn1_funct7 = funct7;
  assign fn1_in1 = cmd_payload_inputs_1;
  assign fn1_in0 = cmd_payload_inputs_0;
  assign \funct7$28  = funct7;
  assign fn0_in1 = cmd_payload_inputs_1;
  assign fn0_in0 = cmd_payload_inputs_0;
  assign \start$26  = \$signal$27 ;
  assign \$signal$25  = fallback7_done;
  assign \$signal$24  = fallback7_output;
  assign \start$22  = \$signal$23 ;
  assign \$signal$21  = fallback6_done;
  assign \$signal$20  = fallback6_output;
  assign \start$18  = \$signal$19 ;
  assign \$signal$17  = fallback5_done;
  assign \$signal$16  = fallback5_output;
  assign \start$14  = \$signal$15 ;
  assign \$signal$13  = fallback4_done;
  assign \$signal$12  = fallback4_output;
  assign start = \$signal$11 ;
  assign \$signal$10  = fallback3_done;
  assign \$signal$9  = fallback3_output;
  assign fn2_start = \$signal$8 ;
  assign \$signal$7  = fn2_done;
  assign \$signal$6  = fn2_output;
  assign fn1_start = \$signal$5 ;
  assign \$signal$4  = fn1_done;
  assign \$signal$3  = fn1_output;
  assign fn0_start = \$signal$2 ;
  assign \$signal$1  = fn0_done;
  assign \$signal  = fn0_output;
  assign funct7 = cmd_payload_function_id[9:3];
  assign funct3 = cmd_payload_function_id[2:0];
endmodule

(* \amaranth.hierarchy  = "Cfu.fallback3" *)
(* generator = "Amaranth" *)
module fallback3(done, in0, in1, \output );
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  output done;
  wire done;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  input [31:0] in0;
  wire [31:0] in0;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:54" *)
  wire [31:0] in0s;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  input [31:0] in1;
  wire [31:0] in1;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:55" *)
  wire [31:0] in1s;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  output [31:0] \output ;
  wire [31:0] \output ;
  assign in1s = in1;
  assign in0s = in0;
  assign done = 1'h1;
  assign \output  = in0;
endmodule

(* \amaranth.hierarchy  = "Cfu.fallback4" *)
(* generator = "Amaranth" *)
module fallback4(done, in0, in1, \output );
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  output done;
  wire done;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  input [31:0] in0;
  wire [31:0] in0;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:54" *)
  wire [31:0] in0s;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  input [31:0] in1;
  wire [31:0] in1;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:55" *)
  wire [31:0] in1s;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  output [31:0] \output ;
  wire [31:0] \output ;
  assign in1s = in1;
  assign in0s = in0;
  assign done = 1'h1;
  assign \output  = in0;
endmodule

(* \amaranth.hierarchy  = "Cfu.fallback5" *)
(* generator = "Amaranth" *)
module fallback5(done, in0, in1, \output );
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  output done;
  wire done;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  input [31:0] in0;
  wire [31:0] in0;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:54" *)
  wire [31:0] in0s;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  input [31:0] in1;
  wire [31:0] in1;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:55" *)
  wire [31:0] in1s;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  output [31:0] \output ;
  wire [31:0] \output ;
  assign in1s = in1;
  assign in0s = in0;
  assign done = 1'h1;
  assign \output  = in0;
endmodule

(* \amaranth.hierarchy  = "Cfu.fallback6" *)
(* generator = "Amaranth" *)
module fallback6(done, in0, in1, \output );
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  output done;
  wire done;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  input [31:0] in0;
  wire [31:0] in0;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:54" *)
  wire [31:0] in0s;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  input [31:0] in1;
  wire [31:0] in1;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:55" *)
  wire [31:0] in1s;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  output [31:0] \output ;
  wire [31:0] \output ;
  assign in1s = in1;
  assign in0s = in0;
  assign done = 1'h1;
  assign \output  = in0;
endmodule

(* \amaranth.hierarchy  = "Cfu.fallback7" *)
(* generator = "Amaranth" *)
module fallback7(done, in0, in1, \output );
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  output done;
  wire done;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  input [31:0] in0;
  wire [31:0] in0;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:54" *)
  wire [31:0] in0s;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  input [31:0] in1;
  wire [31:0] in1;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:55" *)
  wire [31:0] in1s;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  output [31:0] \output ;
  wire [31:0] \output ;
  assign in1s = in1;
  assign in0s = in0;
  assign done = 1'h1;
  assign \output  = in0;
endmodule

(* \amaranth.hierarchy  = "Cfu.fn0" *)
(* generator = "Amaranth" *)
module fn0(done, start, in0, in1, rst, clk, \output );
  reg \$auto$verilog_backend.cc:2083:dump_module$2  = 0;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:70" *)
  wire [15:0] \$1 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:70" *)
  wire [15:0] \$11 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:70" *)
  wire [8:0] \$12 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:70" *)
  wire [15:0] \$16 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:70" *)
  wire [8:0] \$17 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:70" *)
  wire [8:0] \$2 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:70" *)
  wire [15:0] \$6 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:70" *)
  wire [8:0] \$7 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:67" *)
  wire [15:0] \$signal ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:67" *)
  wire [15:0] \$signal$10 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:67" *)
  wire [15:0] \$signal$15 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:67" *)
  wire [15:0] \$signal$5 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/third_party/python/amaranth/amaranth/hdl/ir.py:527" *)
  input clk;
  wire clk;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  output done;
  reg done = 1'h0;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  reg \done$next ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  input [31:0] in0;
  wire [31:0] in0;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:54" *)
  wire [31:0] in0s;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  input [31:0] in1;
  wire [31:0] in1;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:55" *)
  wire [31:0] in1s;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  output [31:0] \output ;
  reg [31:0] \output  = 32'd0;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  reg [31:0] \output$next ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/third_party/python/amaranth/amaranth/hdl/ir.py:527" *)
  input rst;
  wire rst;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:52" *)
  input start;
  wire start;
  assign \$12  = $signed(in0[23:16]) + (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:70" *) $signed(in1[23:16]);
  assign \$11  = + (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:70" *) $signed(\$12 );
  assign \$17  = $signed(in0[31:24]) + (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:70" *) $signed(in1[31:24]);
  assign \$16  = + (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:70" *) $signed(\$17 );
  always @(posedge clk)
    done <= \done$next ;
  always @(posedge clk)
    \output  <= \output$next ;
  assign \$2  = $signed(in0[7:0]) + (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:70" *) $signed(in1[7:0]);
  assign \$1  = + (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:70" *) $signed(\$2 );
  assign \$7  = $signed(in0[15:8]) + (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:70" *) $signed(in1[15:8]);
  assign \$6  = + (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:70" *) $signed(\$7 );
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$2 ) begin end
    \done$next  = 1'h0;
    (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:74" *)
    casez (start)
      /* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:74" */
      1'h1:
          \done$next  = 1'h1;
    endcase
    (* src = "/home/centurion/Documents/Diploma/CFU-Playground/third_party/python/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \done$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$2 ) begin end
    \output$next  = \output ;
    (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:74" *)
    casez (start)
      /* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:74" */
      1'h1:
        begin
          \output$next [7:0] = \$signal [7:0];
          \output$next [15:8] = \$signal$5 [7:0];
          \output$next [23:16] = \$signal$10 [7:0];
          \output$next [31:24] = \$signal$15 [7:0];
        end
    endcase
    (* src = "/home/centurion/Documents/Diploma/CFU-Playground/third_party/python/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \output$next  = 32'd0;
    endcase
  end
  assign in1s = in1;
  assign in0s = in0;
  assign \$signal$15  = \$16 ;
  assign \$signal$10  = \$11 ;
  assign \$signal$5  = \$6 ;
  assign \$signal  = \$1 ;
endmodule

(* \amaranth.hierarchy  = "Cfu.fn1" *)
(* generator = "Amaranth" *)
module fn1(done, start, in0, in1, funct7, rst, clk, \output );
  reg \$auto$verilog_backend.cc:2083:dump_module$3  = 0;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:93" *)
  wire [15:0] \$1 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:93" *)
  wire [15:0] \$10 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/third_party/python/amaranth/amaranth/hdl/dsl.py:437" *)
  wire \$12 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:93" *)
  wire [15:0] \$4 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:93" *)
  wire [15:0] \$7 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:90" *)
  wire [15:0] \$signal ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:90" *)
  wire [15:0] \$signal$3 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:90" *)
  wire [15:0] \$signal$6 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:90" *)
  wire [15:0] \$signal$9 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/third_party/python/amaranth/amaranth/hdl/ir.py:527" *)
  input clk;
  wire clk;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  output done;
  reg done = 1'h0;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  reg \done$next ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:50" *)
  input [6:0] funct7;
  wire [6:0] funct7;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  input [31:0] in0;
  wire [31:0] in0;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:54" *)
  wire [31:0] in0s;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  input [31:0] in1;
  wire [31:0] in1;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:55" *)
  wire [31:0] in1s;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  output [31:0] \output ;
  reg [31:0] \output  = 32'd0;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  reg [31:0] \output$next ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/third_party/python/amaranth/amaranth/hdl/ir.py:527" *)
  input rst;
  wire rst;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:52" *)
  input start;
  wire start;
  assign \$10  = $signed(in0[31:24]) * (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:93" *) $signed(in1[31:24]);
  assign \$12  = | (* src = "/home/centurion/Documents/Diploma/CFU-Playground/third_party/python/amaranth/amaranth/hdl/dsl.py:437" *) funct7;
  always @(posedge clk)
    done <= \done$next ;
  always @(posedge clk)
    \output  <= \output$next ;
  assign \$1  = $signed(in0[7:0]) * (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:93" *) $signed(in1[7:0]);
  assign \$4  = $signed(in0[15:8]) * (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:93" *) $signed(in1[15:8]);
  assign \$7  = $signed(in0[23:16]) * (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:93" *) $signed(in1[23:16]);
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$3 ) begin end
    \done$next  = 1'h0;
    (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:97" *)
    casez (start)
      /* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:97" */
      1'h1:
          \done$next  = 1'h1;
    endcase
    (* src = "/home/centurion/Documents/Diploma/CFU-Playground/third_party/python/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \done$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$3 ) begin end
    \output$next  = \output ;
    (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:97" *)
    casez (start)
      /* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:97" */
      1'h1:
          (* full_case = 32'd1 *)
          (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:101" *)
          casez (\$12 )
            /* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:101" */
            1'h1:
              begin
                \output$next [15:0] = \$signal$6 ;
                \output$next [31:16] = \$signal$9 ;
              end
            /* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:107" */
            default:
              begin
                \output$next [15:0] = \$signal ;
                \output$next [31:16] = \$signal$3 ;
              end
          endcase
    endcase
    (* src = "/home/centurion/Documents/Diploma/CFU-Playground/third_party/python/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \output$next  = 32'd0;
    endcase
  end
  assign in1s = in1;
  assign in0s = in0;
  assign \$signal$9  = \$10 ;
  assign \$signal$6  = \$7 ;
  assign \$signal$3  = \$4 ;
  assign \$signal  = \$1 ;
endmodule

(* \amaranth.hierarchy  = "Cfu.fn2" *)
(* generator = "Amaranth" *)
module fn2(done, start, in0, in1, rst, clk, \output );
  reg \$auto$verilog_backend.cc:2083:dump_module$4  = 0;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:124" *)
  wire [16:0] \$1 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:131" *)
  wire [17:0] \$11 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:124" *)
  wire [16:0] \$2 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:124" *)
  wire [16:0] \$5 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:124" *)
  wire [16:0] \$6 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:131" *)
  wire [31:0] \$8 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:131" *)
  wire [16:0] \$9 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:121" *)
  wire [15:0] \$signal ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:121" *)
  wire [15:0] \$signal$4 ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/third_party/python/amaranth/amaranth/hdl/ir.py:527" *)
  input clk;
  wire clk;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  output done;
  reg done = 1'h0;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  reg \done$next ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  input [31:0] in0;
  wire [31:0] in0;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:54" *)
  wire [31:0] in0s;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  input [31:0] in1;
  wire [31:0] in1;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:55" *)
  wire [31:0] in1s;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  output [31:0] \output ;
  reg [31:0] \output  = 32'd0;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  reg [31:0] \output$next ;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/third_party/python/amaranth/amaranth/hdl/ir.py:527" *)
  input rst;
  wire rst;
  (* src = "/home/centurion/Documents/Diploma/CFU-Playground/python/amaranth_cfu/cfu.py:52" *)
  input start;
  wire start;
  assign \$9  = $signed(16'h0000) + (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:131" *) $signed(\$signal );
  assign \$11  = $signed(\$9 ) + (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:131" *) $signed(\$signal$4 );
  assign \$8  = + (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:131" *) $signed(\$11 );
  always @(posedge clk)
    done <= \done$next ;
  always @(posedge clk)
    \output  <= \output$next ;
  assign \$2  = $signed(in0[15:0]) + (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:124" *) $signed(in1[15:0]);
  assign \$6  = $signed(in0[31:16]) + (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:124" *) $signed(in1[31:16]);
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$4 ) begin end
    \done$next  = 1'h0;
    (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:128" *)
    casez (start)
      /* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:128" */
      1'h1:
          \done$next  = 1'h1;
    endcase
    (* src = "/home/centurion/Documents/Diploma/CFU-Playground/third_party/python/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \done$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$4 ) begin end
    \output$next  = \output ;
    (* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:128" *)
    casez (start)
      /* src = "/home/centurion/Documents/Diploma/CFU-Playground/proj/simple_simd_ext/cfu.py:128" */
      1'h1:
          \output$next  = \$8 ;
    endcase
    (* src = "/home/centurion/Documents/Diploma/CFU-Playground/third_party/python/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \output$next  = 32'd0;
    endcase
  end
  assign \$1  = \$2 ;
  assign \$5  = \$6 ;
  assign in1s = in1;
  assign in0s = in0;
  assign \$signal$4  = \$6 [15:0];
  assign \$signal  = \$2 [15:0];
endmodule
